### ISSUE TITLE
Latest CircuitPython and Libraries are too large to run on Seeduino Xiao

### ISSUE THREAD

**Issue by scarolan** [educ8s/CircuitPython-Light-Meter-OLED#1]
This error shows up when we try to load the required mpy libraries.  Just 60 bytes too large now...

```
MemoryError: memory allocation failed, allocating 60 bytes
```

**Comment by educ8s** [comment]
Yes, I just tried it. It seems that libraries grew in size since the time I developed the video and they no longer work with the original Xiao Board.

**Comment by scarolan** [comment]
Ok, we can close this out then since it's an upstream issue.
